version: 2.1

jobs:
  "leap-15.2":
    docker:
        - image: opensuse/leap:15.2
    steps:
      - checkout
      - run:
          name: Setup Dev
          command: ./tools/setup-dev.sh
          
  "tumbleweed":
    docker:
        - image: opensuse/tumbleweed:latest
    steps:
      - checkout
      - run:
          name: Setup Dev
          command: ./tools/setup-dev.sh

workflows:
  version: 2
  build:
    jobs:
      - "tumbleweed"
